# Generated by Django 5.1.6 on 2025-02-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user2',
            new_name='user3',
        ),
        migrations.AlterModelTable(
            name='user3',
            table='user3',
        ),
    ]
