# Generated by Django 5.1.6 on 2025-02-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_user2_user3_alter_user3_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user3',
            old_name='name',
            new_name='fullname',
        ),
    ]
