# Generated by Django 5.1.6 on 2025-02-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_user4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user4',
            new_name='user5',
        ),
    ]
