# Generated by Django 5.1.6 on 2025-03-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_user4_user5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user5',
            new_name='user6',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AlterModelTable(
            name='user6',
            table='user6',
        ),
    ]
